# Generated by Django 4.2.7 on 2025-11-05 13:13

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(help_text='create, update, delete, view', max_length=50, verbose_name='Eylem')),
                ('object_type', models.CharField(max_length=100, verbose_name='Nesne Tipi')),
                ('object_id', models.CharField(max_length=100, verbose_name='Nesne ID')),
                ('changes', models.JSONField(blank=True, null=True, verbose_name='Değişiklikler')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP Adresi')),
                ('user_agent', models.TextField(blank=True, null=True, verbose_name='User Agent')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Zaman')),
            ],
            options={
                'verbose_name': 'Denetim Kaydı',
                'verbose_name_plural': 'Denetim Kayıtları',
                'db_table': 'audit_logs',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Şube Adı')),
                ('address', models.TextField(verbose_name='Adres')),
                ('phone', models.CharField(max_length=30, verbose_name='Telefon')),
                ('email', models.EmailField(max_length=254, verbose_name='E-posta')),
                ('sgk_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='SGK Numarası')),
                ('metadata', models.JSONField(blank=True, default=dict, null=True, verbose_name='Ek Bilgiler')),
            ],
            options={
                'verbose_name': 'Şube',
                'verbose_name_plural': 'Şubeler',
                'db_table': 'branches',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Marka Adı')),
                ('tax_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='Vergi Numarası')),
                ('phone', models.CharField(blank=True, max_length=30, null=True, verbose_name='Telefon')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-posta')),
                ('branch_count', models.IntegerField(default=0, help_text='Otomatik hesaplanır', verbose_name='Şube Sayısı')),
                ('metadata', models.JSONField(blank=True, default=dict, null=True, verbose_name='Ek Bilgiler')),
            ],
            options={
                'verbose_name': 'Marka',
                'verbose_name_plural': 'Markalar',
                'db_table': 'brands',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(help_text='Resmi şirket ünvanı', max_length=255, verbose_name='Şirket Ünvanı')),
                ('tax_number', models.CharField(max_length=50, unique=True, validators=[django.core.validators.RegexValidator(message='Vergi numarası 10 haneli olmalıdır', regex='^\\d{10}$')], verbose_name='Vergi Numarası')),
                ('email', models.EmailField(max_length=254, verbose_name='E-posta')),
                ('iban', models.CharField(blank=True, max_length=34, null=True, validators=[django.core.validators.RegexValidator(message='Geçerli bir TR IBAN giriniz', regex='^TR\\d{24}$')], verbose_name='IBAN')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Açıklama')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('metadata', models.JSONField(blank=True, default=dict, null=True, verbose_name='Ek Bilgiler')),
            ],
            options={
                'verbose_name': 'Şirket',
                'verbose_name_plural': 'Şirketler',
                'db_table': 'companies',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=255, verbose_name='Ad Soyad')),
                ('national_id', models.CharField(blank=True, max_length=11, null=True, validators=[django.core.validators.RegexValidator(message='TC Kimlik numarası 11 haneli olmalıdır', regex='^\\d{11}$')], verbose_name='TC Kimlik No')),
                ('address', models.TextField(blank=True, null=True, verbose_name='Adres')),
                ('phone', models.CharField(blank=True, max_length=30, null=True, verbose_name='Telefon')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-posta')),
                ('iban', models.CharField(blank=True, max_length=34, null=True, validators=[django.core.validators.RegexValidator(message='Geçerli bir TR IBAN giriniz', regex='^TR\\d{24}$')], verbose_name='IBAN')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Açıklama')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='people', to='core.branch', verbose_name='Şube')),
            ],
            options={
                'verbose_name': 'Kişi',
                'verbose_name_plural': 'Kişiler',
                'db_table': 'people',
                'ordering': ['full_name'],
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Rol Adı')),
                ('display_name', models.CharField(max_length=100, verbose_name='Görünen Ad')),
                ('permissions', models.JSONField(blank=True, default=dict, help_text='JSON formatında yetki seti', null=True, verbose_name='Yetkiler')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Açıklama')),
            ],
            options={
                'verbose_name': 'Rol',
                'verbose_name_plural': 'Roller',
                'db_table': 'roles',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, verbose_name='Başlık')),
                ('content', models.TextField(blank=True, null=True, verbose_name='İçerik Özeti')),
                ('file', models.FileField(blank=True, null=True, upload_to='reports/%Y/%m/', verbose_name='Dosya')),
                ('report_type', models.CharField(choices=[('daily', 'Günlük'), ('weekly', 'Haftalık'), ('monthly', 'Aylık'), ('yearly', 'Yıllık'), ('custom', 'Özel')], max_length=20, verbose_name='Rapor Türü')),
                ('scope', models.CharField(choices=[('company', 'Şirket'), ('brand', 'Marka'), ('branch', 'Şube'), ('person', 'Kişi')], max_length=20, verbose_name='Kapsam')),
                ('report_date', models.DateField(verbose_name='Rapor Tarihi')),
                ('tags', models.JSONField(blank=True, default=list, null=True, verbose_name='Etiketler')),
                ('metadata', models.JSONField(blank=True, default=dict, null=True, verbose_name='Meta Veri')),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='core.branch')),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='core.brand')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='core.company')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_reports', to=settings.AUTH_USER_MODEL, verbose_name='Oluşturan')),
                ('person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='core.person')),
            ],
            options={
                'verbose_name': 'Rapor',
                'verbose_name_plural': 'Raporlar',
                'db_table': 'reports',
                'ordering': ['-report_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PromissoryNote',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, verbose_name='Başlık')),
                ('note_number', models.CharField(max_length=100, unique=True, verbose_name='Senet Numarası')),
                ('file', models.FileField(blank=True, null=True, upload_to='promissory_notes/%Y/%m/', verbose_name='Dosya')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Tutar')),
                ('due_date', models.DateField(verbose_name='Vade Tarihi')),
                ('payment_status', models.CharField(choices=[('pending', 'Beklemede'), ('paid', 'Ödendi'), ('overdue', 'Vadesi Geçti')], default='pending', max_length=20, verbose_name='Ödeme Durumu')),
                ('metadata', models.JSONField(blank=True, default=dict, null=True, verbose_name='Meta Veri')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_notes', to=settings.AUTH_USER_MODEL, verbose_name='Oluşturan')),
                ('related_branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='promissory_notes', to='core.branch')),
                ('related_brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='promissory_notes', to='core.brand')),
                ('related_company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='promissory_notes', to='core.company')),
                ('related_person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='promissory_notes', to='core.person')),
            ],
            options={
                'verbose_name': 'Senet',
                'verbose_name_plural': 'Senetler',
                'db_table': 'promissory_notes',
                'ordering': ['due_date', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='person',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='people', to='core.role', verbose_name='Rol'),
        ),
        migrations.CreateModel(
            name='FinancialRecord',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, verbose_name='Başlık')),
                ('type', models.CharField(choices=[('income', 'Gelir'), ('expense', 'Gider'), ('turnover', 'Ciro'), ('profit_share', 'Kar Payı')], max_length=20, verbose_name='Tür')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Tutar')),
                ('currency', models.CharField(choices=[('TRY', 'Türk Lirası'), ('USD', 'Amerikan Doları'), ('EUR', 'Euro'), ('GBP', 'İngiliz Sterlini')], default='TRY', max_length=3, verbose_name='Para Birimi')),
                ('date', models.DateField(verbose_name='Tarih')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Açıklama')),
                ('attachments', models.FileField(blank=True, null=True, upload_to='financial_records/%Y/%m/', verbose_name='Ekler')),
                ('metadata', models.JSONField(blank=True, default=dict, null=True, verbose_name='Meta Veri')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_financial_records', to=settings.AUTH_USER_MODEL, verbose_name='Oluşturan')),
                ('related_branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='financial_records', to='core.branch')),
                ('related_brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='financial_records', to='core.brand')),
                ('related_company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='financial_records', to='core.company')),
                ('related_person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='financial_records', to='core.person')),
            ],
            options={
                'verbose_name': 'Mali Kayıt',
                'verbose_name_plural': 'Mali Kayıtlar',
                'db_table': 'financial_records',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, verbose_name='Başlık')),
                ('contract_number', models.CharField(max_length=100, unique=True, verbose_name='Sözleşme Numarası')),
                ('template_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Şablon Adı')),
                ('file', models.FileField(upload_to='contracts/%Y/%m/', verbose_name='Dosya')),
                ('start_date', models.DateField(verbose_name='Başlangıç Tarihi')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Bitiş Tarihi')),
                ('status', models.CharField(choices=[('draft', 'Taslak'), ('active', 'Aktif'), ('expired', 'Süresi Dolmuş'), ('terminated', 'Feshedilmiş')], default='draft', max_length=20, verbose_name='Durum')),
                ('versioning', models.JSONField(blank=True, default=dict, null=True, verbose_name='Versiyon Geçmişi')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_contracts', to=settings.AUTH_USER_MODEL, verbose_name='Oluşturan')),
                ('related_branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='core.branch')),
                ('related_brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='core.brand')),
                ('related_company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='core.company')),
                ('related_person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='core.person')),
            ],
            options={
                'verbose_name': 'Sözleşme',
                'verbose_name_plural': 'Sözleşmeler',
                'db_table': 'contracts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='company',
            index=models.Index(fields=['tax_number'], name='companies_tax_num_172cb7_idx'),
        ),
        migrations.AddIndex(
            model_name='company',
            index=models.Index(fields=['title'], name='companies_title_995b48_idx'),
        ),
        migrations.AddIndex(
            model_name='company',
            index=models.Index(fields=['is_active'], name='companies_is_acti_e9a12b_idx'),
        ),
        migrations.AddField(
            model_name='brand',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brands', to='core.company', verbose_name='Şirket'),
        ),
        migrations.AddField(
            model_name='branch',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branches', to='core.brand', verbose_name='Marka'),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='actor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['report_type'], name='reports_report__ff8b25_idx'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['report_date'], name='reports_report__65f2df_idx'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['scope'], name='reports_scope_40aff6_idx'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['company'], name='reports_company_66d317_idx'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['brand'], name='reports_brand_i_fb82ae_idx'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['branch'], name='reports_branch__0c2ba3_idx'),
        ),
        migrations.AddIndex(
            model_name='promissorynote',
            index=models.Index(fields=['note_number'], name='promissory__note_nu_1fe214_idx'),
        ),
        migrations.AddIndex(
            model_name='promissorynote',
            index=models.Index(fields=['payment_status'], name='promissory__payment_c3637f_idx'),
        ),
        migrations.AddIndex(
            model_name='promissorynote',
            index=models.Index(fields=['due_date'], name='promissory__due_dat_1fd9b6_idx'),
        ),
        migrations.AddIndex(
            model_name='person',
            index=models.Index(fields=['branch', 'full_name'], name='people_branch__9dc0be_idx'),
        ),
        migrations.AddIndex(
            model_name='person',
            index=models.Index(fields=['role'], name='people_role_id_d1aaed_idx'),
        ),
        migrations.AddIndex(
            model_name='person',
            index=models.Index(fields=['is_active'], name='people_is_acti_998405_idx'),
        ),
        migrations.AddIndex(
            model_name='financialrecord',
            index=models.Index(fields=['type'], name='financial_r_type_161a00_idx'),
        ),
        migrations.AddIndex(
            model_name='financialrecord',
            index=models.Index(fields=['date'], name='financial_r_date_c7ef46_idx'),
        ),
        migrations.AddIndex(
            model_name='financialrecord',
            index=models.Index(fields=['currency'], name='financial_r_currenc_579c8c_idx'),
        ),
        migrations.AddIndex(
            model_name='contract',
            index=models.Index(fields=['contract_number'], name='contracts_contrac_bb0c23_idx'),
        ),
        migrations.AddIndex(
            model_name='contract',
            index=models.Index(fields=['status'], name='contracts_status_093df1_idx'),
        ),
        migrations.AddIndex(
            model_name='contract',
            index=models.Index(fields=['start_date'], name='contracts_start_d_b96943_idx'),
        ),
        migrations.AddIndex(
            model_name='contract',
            index=models.Index(fields=['end_date'], name='contracts_end_dat_9bf3b4_idx'),
        ),
        migrations.AddIndex(
            model_name='brand',
            index=models.Index(fields=['company', 'name'], name='brands_company_5a71b9_idx'),
        ),
        migrations.AddConstraint(
            model_name='brand',
            constraint=models.UniqueConstraint(fields=('company', 'name'), name='unique_brand_per_company'),
        ),
        migrations.AddIndex(
            model_name='branch',
            index=models.Index(fields=['brand', 'name'], name='branches_brand_i_b29e06_idx'),
        ),
        migrations.AddConstraint(
            model_name='branch',
            constraint=models.UniqueConstraint(fields=('brand', 'name'), name='unique_branch_per_brand'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['actor'], name='audit_logs_actor_i_0badd2_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['action'], name='audit_logs_action_31f574_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['object_type'], name='audit_logs_object__69dfc3_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['timestamp'], name='audit_logs_timesta_423be6_idx'),
        ),
    ]
